### ISSUE TITLE
face-detectable sub-dataset of Gaze360

### ISSUE THREAD

**Issue by zorazll** [zgchen33/MCGaze#1]
Thank you for the author's work. I would like to inquire about where you obtained the subset of Gaze360, specifically the Front facing and Front 180°. Did you create this subset yourself? If there is a way to download it, could you please provide a link? Thank you very much!

**Comment by 1ranGuan** [comment]
Thank you for your interest in our work. Regarding the subset of the GAZE360 dataset, we used the `metadata.mat` file in the GAZE360 dataset, which has bbox annotations for faces, eyes, and for images where faces could not be detected, the corresponding bboxes do not exist. When we select the images in the subset, we filter out the images for which the bbox annotation exists. The original GAZE360 dataset can be processed using our `tools/gaze360_img_reorganize.py` code.

**Comment by zorazll** [comment]
Thank you for your answer!
