### ISSUE TITLE
ONNX conversion support

### ISSUE THREAD

**Issue by Sadat75** [zgchen33/MCGaze#10]
Dear @zgchen33,

Thank you for this repository. I have tested the gaze estimation models, and the results are pretty impressive. I want to convert them to ONNX. Could you please provide any information or guidelines regarding the ONNX conversion of the gaze models?

Thank you.

**Comment by zgchen33** [comment]
Thank you for your interest! 
However, we don't have experience with the ONNX conversion of the gaze models.
