### ISSUE TITLE
Annotations truncated, tools/gaze360_img_reorganize.py bugs

### ISSUE THREAD

**Issue by oreillyj-cse** [zgchen33/MCGaze#2]
Major: What exact environment are you using? Having a lot of trouble on Ubuntu 20.04 with Python 3.9.18

Major: The .json files in the linked (https://drive.google.com/drive/folders/1tNvXMn52bth8zSCGZK_syP6gdt7VLjGq) Google Drive with the COCO annotations for gaze360 (not l2cs) appear to be truncated at exactly 64KB for both train and test. Also, Why not just dump into repo?

**Is the tools/gaze360_img_reorganize.py correct, newest version? If not, then perhaps can ignore the rest.** 

Major: in tools/gaze360_img_reorganize.py: You have a splits list at 16 and reuse name at 23…. Mine is crashing and renaming line 16 splits to splits2 and also at 19. Renaming allows it to proceed.

In tools/gaze360_img_reorganize.py: Not really clear what origt is: figured out, I think, that it needs to point at the dataset repo’s (https://github.com/Erkil1452/gaze360) code directory, but not 100%.

Major:
In tools/gaze360_img_reorganize.py: Line 29 
ori_gt_path = os.path.join(origt , f"/{split}.txt")
is not working for me. Changing to 
	ori_gt_path = os.path.join(origt, split+'.txt')
fixes it. It, at least looks basically right for the data/gaze360 directory but data/l2cs directories are almost all empty. 

Minor: in the bash scripts for training, had to reset CUDA_VISIBLE_DEVICES to start. 

Probably Minor: Training doesn’t start. I get a No such file or directory error like “FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data2/MCGaze/data/l2cs/train_rawframes/1612/00061.png'” (path down to train_rawframes is correct but image is not there). My lack of confidence in the dataset setup ( tools/gaze360_img_reorganize.py, annotations, and origt directory suggests the issue may be upstream).

**Comment by zgchen33** [comment]
Thank you for your issue. We will fix the problems next week and make sure the dataset setup is true. Again, thank you for the questions.

**Comment by oreillyj-cse** [comment]
In lieu of opening another issue, I’m going to just add to this one:
1)	Update (fixed for gaze360/”Full”)
2)	calculate_mae_gaze360.py: Testing issues (probably should open another issue but I feel might be fixable)
3)	Updated file does not seem to work for L2CS
4)	Ubuntu 20.04 issues and fixes (and a moderate number of absolute path issues)
5)     tools/test_gaze360.sh --evafile?

Given some fairly obvious issues across multiple files, this is starting to feel like your local files are different than what's on GitHub (I'm not complaining, I understand fully how this can happen as I imagine the preprocessing/reorganizing was done a long time ago, etc.): Depending on your current setup and since the training and testing appear quite efficient, it seems that it might be reasonable to do a full reorganize, train, test series for both L2CS and Full to make sure that you have the right set of code and then copy your code somewhere and then delete directories not necessary for GitHub (like data) and then **diff -qr your_working_code github_code**. Not quick exactly, but I think this wouldn't require much active attention if there are no issues.

Thanks, explanations of the issues/comments listed above are below. 

**1) Update (fixed for gaze360/”Full”)**

- That seemed to help for gaze360. I redownloaded it and eventually got it to run and train (with a little work).
- I still had to “In tools/gaze360_img_reorganize.py: Not really clear what origt is: figured out, I think, that it needs to point at the dataset repo’s (https://github.com/Erkil1452/gaze360) code directory, but not 100%.” As before. 
- I had to adjust the batch size under MCGaze/configs/_base_/datasets ( samples_per_gpu=12, instead of 32) as I have a 1080Ti (will use 2 shortly). I should probably increase the number of training iterations but that’s a detail for when I can get it to test.
- Training time was quite reasonable and testing seemed to almost complete, see below:

**2)	calculate_mae_gaze360.py: Testing issues (probably should open another issue but I feel might be fixable)**
For testing, I’m getting the issue where an assertion is being thrown from tools/calculate_mae_gaze360.py (presumably from a call from tools/test_gaze360.py). I believe it fully ran through the tests but then, when calculating the MAE is finding an error. I added a few prints, so the line for the insertion is probably 123 in tools/calculate_mae_gaze360.py. One odd thing is that it prints twice. I tested both with your weights and my weights. Output:
  warnings.warn('No positional inputs found for a module, '
100%|█████████████████████████████████████████| 517/517 [07:44<00:00,  1.11it/s]
Done
2023-11-29 12:00:18
len(gaze_gt)194
len(gaze_pred)194
len(gaze_gt)194
len(gaze_pred)37
Traceback (most recent call last):
  File "/mnt/data2/MCGaze/tools/calculate_mae_gaze360.py", line 200, in <module>
    main(args)
  File "/mnt/data2/MCGaze/tools/calculate_mae_gaze360.py", line 104, in main
    gaze_error(eval_data, anno_data, 'fusion_gazes')
  File "/mnt/data2/MCGaze/tools/calculate_mae_gaze360.py", line 125, in gaze_error
    assert len(gaze_gt) == len(gaze_pred)
AssertionError

**3)	Updated file does not seem to work for L2CS**
For L2CS and tools/gaze360_img_reorganize.py, the data is output to directory MCGaze/data/data/l2cs (which looks off as Full is MCGaze/data/gaze360); I’m assuming the gaze 360 is correct (at 9.5 GB) but l2cs is not (at 21.6MB) changing 
target_dataset_roots = ['data/gaze360/', 'data/data/l2cs'] 
to
 target_dataset_roots = ['data/gaze360/', 'data/l2cs'] 
did not seem to have an effect.   I even tried copying the test_rawframes and train_rawframes from data/gaze360 and merging them into data/l2cs but that also did not appear to work, still getting some errors like “FileNotFoundError: [Errno 2] No such file or directory: 'data/l2cs/train_rawframes/77/00175.png'”

**4)	Ubuntu 20.04 issues and fixes (and a moderate number of absolute path issues)**
Minor issues (with quick fixes):

- On Ubuntu 20.04 I had a few issues. I forget the exact errors given but to get training started I had to make some changes:
- I added, after imports and froms in train.py
   **import torch.multiprocessing**
  **torch.multiprocessing.set_sharing_strategy('file_system')**
  and set maximum file descriptors to 2048 with
    **ulimit -n 2048** .
- There were several places in training and testing where I had to change absolute paths to relative, generally “/data/…” to “data/…”, mostly in the bash scripts but also multiclue_gaze_r50_l2cs.py .

**5)     tools/test_gaze360.sh --evafile?**
Also, I think, tools/test_gaze360.sh should have a change from “--evafile"  to “--evalfile"

**Comment by zgchen33** [comment]
Sorry, I was a little busy before. For your issues, we already fixed them. Here are some details about them.
1. The right version of Google Drive with the COCO annotations for gaze360 (not l2cs) was already updated.

2. The file "tools/gaze360_img_reorganize.py" has been updated.

3. Regarding the error of "calculate_mae_gaze360.py", I think you may need to check if the testing files' paths are right because there are two settings. For example, if you trained the model with the L2CS setting, you need to use [calculate_mae_l2cs.py](https://github.com/zgchen33/MCGaze/blob/master/tools/calculate_mae_l2cs.py) for evaluation.

4. The problem of some absolute paths has been fixed.

5. Also, tools/test_gaze360.sh already have a change from “--evafile" to “--evalfile".

Again, thank you for your issues to help us improve this repo's quality.
