### ISSUE TITLE
inference script

### ISSUE THREAD

**Issue by HeChengHui** [zgchen33/MCGaze#3]
@zgchen33 

Thank you for your work! 
Does this work with a live streaming input? And is it possible to add an inference script to test on our own videos?

**Comment by zgchen33** [comment]
To test your videos, you can refer to [MCGaze_demo](https://github.com/zgchen33/MCGaze/tree/master/MCGaze_demo).

**Comment by HeChengHui** [comment]
@zgchen33 

would this work for live stream process?

**Comment by 1ranGuan** [comment]
We currently only support gaze annotation through video post-processing.
