### ISSUE TITLE
Problem about gaze360_img_reorganize.py

### ISSUE THREAD

**Issue by darlingyou999** [zgchen33/MCGaze#4]
`import os
from tqdm import tqdm
import  cv2
import time
import scipy.io as sio
import numpy as np
import torch

################### you should modify the path to raw gaze360 dataset  ############################
ori_dataset_root = "/21TB/xhx/MCGaze-master/Dataset/gaze360/gaze360_dataset_htrht37t43t9723kdfnJKhf_v2/imgs"
meta_data_root = "/21TB/xhx/MCGaze-master/Dataset/gaze360/gaze360_dataset_htrht37t43t9723kdfnJKhf_v2/metadata.mat"
origt = "/21TB/xhx/MCGaze-master/Dataset/gaze360/gaze360_dataset_htrht37t43t9723kdfnJKhf_v2"
###################################################################################################
dataset_settings = ['FULL', 'L2CS']
target_dataset_roots = ['data/gaze360/', 'data/data/l2cs']
splits = ['train','test']

for dataset_setting, target_dataset_root in zip(dataset_settings, target_dataset_roots):
    for split in splits:
        msg = sio.loadmat(meta_data_root)
        recordings = msg["recordings"]
        face_bbox = msg["person_face_bbox"]
        split_index = msg["split"]
        recording_index = msg["recording"]
        person_index = msg["person_identity"]
        frame_index = msg["frame"]
        total_num = recording_index.shape[1]
        ori_gt_path = os.path.join(origt, f"{split}.txt")`

after i modifyed the path to raw gaze360 ,when i run the gaze360_img_reorganize.py,the following will show
`FileNotFoundError: [Errno 2] No such file or directory: '/21TB/xhx/MCGaze-master/Dataset/gaze360/gaze360_dataset_htrht37t43t9723kdfnJKhf_v2/train.txt'`
i checked the project files and didn't find it.  what's this is? Should i download the train.json and test.json from the link and put it in this file first?
i will read the code line by line first to understand it ,but if you can explain me what's going on ,that would be so nice.Thank you.

**Comment by darlingyou999** [comment]
never mind i found the .text file in the `tools/dataset_converters/gaze360`

**Comment by darlingyou999** [comment]
after i successfully runned the `gaze360_img_reorganize.py`,i sitll can't see the right structure of the dataset

**Comment by darlingyou999** [comment]
never mind i found it

**Comment by darlingyou999** [comment]
i wonder if the .text file needed in the gaze360_img_reorganize.py is the .text file in the  tools/dataset_converters/gaze360.
after i successfully run the tranning code ,the loss is nan. I checked the lr and adjust the batchsize to 2. 
i doubt if i find wrong .text file

**Comment by zgchen33** [comment]
For example, you can change the number of "samples_per_gpu" in the corresponding lines of [multiclue_gaze_r50_l2cs.py](https://github.com/zgchen33/MCGaze/blob/master/configs/multiclue_gaze/multiclue_gaze_r50_l2cs.py).

**Comment by zgchen33** [comment]
> i wonder if the .text file needed in the gaze360_img_reorganize.py is the .text file in the tools/dataset_converters/gaze360. after i successfully run the tranning code ,the loss is nan. I checked the lr and adjust the batchsize to 2. i doubt if i find wrong .text file
Did you follow the dataset‘s reorganization that way? Can you give me more details?

**Comment by darlingyou999** [comment]
i download the raw gaze360 dataset and modifyed the path, but i didn't do this  "indicate the 'dataset_setting' value (i.e., 'L2CS' or 'Full')." Should i do something?  I read the `tools/gaze360_img_reorganize.py` and find it will automatically deal the raw dataset into L2CS version and Full version。
One thing puzzle me most is 28th line of the `tools/gaze360_img_reorganize.py`。
`ori_gt_path = os.path.join(origt, f"{split}.txt")`
the origt is the modify path which should be the "PATH to raw GAZE360 dataset dir eg. DataSet/gaze360/gaze360_dataset_htrht37t43t9723kdfnJKhf_v2"
the 29th line is `f = open(ori_gt_path)`, which means there's a train.txt or a test.txt file . but the raw gaze360 dont have it.

**Comment by zgchen33** [comment]
Yes, you are right. The raw gaze360 dataset doesn't have these files. However, you can find the train.txt or test.txt in [Gaze360's official github repo](https://github.com/erkil1452/gaze360/tree/master/code).

**Comment by darlingyou999** [comment]
` lr: 4.995e-04, eta: 2:38:53, time: 1.566, data_time: 0.028, memory: 2267, stage0_face_loss_cls: 310651.3904, stage0_face_pos_acc: 96.0000, stage0_face_loss_bbox: 1.4338, stage0_face_loss_iou: 0.8454, stage0_eyes_loss_cls: 315805.2175, stage0_eyes_pos_acc: 96.0000, stage0_eyes_loss_bbox: 1.1153, stage0_eyes_loss_iou: 1.2454, stage0_head_loss_cls: 0.0002, stage0_head_pos_acc: 100.0000, stage0_head_loss_bbox: 0.6673, stage0_head_loss_iou: 0.2477, stage0_final_gaze_loss_gaze: 5.0161, stage0_final_gaze_loss_temp: 0.0000, stage0_face_gaze_loss_gaze: nan, stage0_eyes_gaze_loss_gaze: nan, stage0_head_gaze_loss_gaze: 4.9928, stage1_face_loss_cls: 374077.0845, stage1_face_pos_acc: 96.0000, stage1_face_loss_bbox: 1.6756, stage1_face_loss_iou: 0.9565, stage1_eyes_loss_cls: 308871.7827, stage1_eyes_pos_acc: 96.0000, stage1_eyes_loss_bbox: 1.2717, stage1_eyes_loss_iou: 1.3849, stage1_head_loss_cls: 0.0008, stage1_head_pos_acc: 100.0000, stage1_head_loss_bbox: 1.4277, stage1_head_loss_iou: 0.4982, stage1_final_gaze_loss_gaze: 5.0052, stage1_final_gaze_loss_temp: 0.0000, stage1_face_gaze_loss_gaze: nan, stage1_eyes_gaze_loss_gaze: nan, stage1_head_gaze_loss_gaze: 4.9863, stage2_face_loss_cls: 338408.6950, stage2_face_pos_acc: 96.0000, stage2_face_loss_bbox: 1.9657, stage2_face_loss_iou: 1.0776, stage2_eyes_loss_cls: 295201.8106, stage2_eyes_pos_acc: 96.0000, stage2_eyes_loss_bbox: 1.6370, stage2_eyes_loss_iou: 1.5817, stage2_head_loss_cls: 0.0003, stage2_head_pos_acc: 100.0000, stage2_head_loss_bbox: 2.6199, stage2_head_loss_iou: 0.8417, stage2_final_gaze_loss_gaze: 4.8835, stage2_final_gaze_loss_temp: 0.0000, stage2_face_gaze_loss_gaze: nan, stage2_eyes_gaze_loss_gaze: nan, stage2_head_gaze_loss_gaze: 4.9944, stage3_face_loss_cls: 323058.2607, stage3_face_pos_acc: 96.0000, stage3_face_loss_bbox: 2.4255, stage3_face_loss_iou: 1.2906, stage3_eyes_loss_cls: 281386.7505, stage3_eyes_pos_acc: 96.0000, stage3_eyes_loss_bbox: 1.8927, stage3_eyes_loss_iou: 1.6949, stage3_head_loss_cls: 0.0004, stage3_head_pos_acc: 100.0000, stage3_head_loss_bbox: 4.2112, stage3_head_loss_iou: 1.2525, stage3_final_gaze_loss_gaze: 5.0114, stage3_final_gaze_loss_temp: 0.0000, stage3_face_gaze_loss_gaze: nan, stage3_eyes_gaze_loss_gaze: nan, stage3_head_gaze_loss_gaze: 4.9130, loss: nan, grad_norm: 27800429.6938
`
this is the output of the training, i noticed that there's quite a few `nan`. Is this correct？
I read part of your paper and i knew that the whole loss is calculated by the other losses which are head, face, eyes and so on. 
the question is why there's `nan`?

**Comment by zgchen33** [comment]
It is strange. I remember in our training, there wasn't nan.
Did you change the code? Or could you provide more information about your training?

**Comment by darlingyou999** [comment]
I figured it out. I set the samples_per_gpu and workers_per_gpu as 2 which leads to a too small batchsize. Now, I changed both of these into 8, and i can successfully train the code. 
Thank you for all you patience of helping me.
I appreciate it.

**Comment by zgchen33** [comment]
You are welcome! Thank you for your interest in this work.
I close this issue now. If you have any problem, you can reopen this issue or just create a new issue.
