### ISSUE TITLE
I installed MMCV==1.4.8 but the dependencies of the program requires mmvc>=2.0.0rc4, <2.2.0

### ISSUE THREAD

**Issue by BmonsterYJ** [zgchen33/MCGaze#6]
Thanks a lot to the authors for the wonderful work. I have some quick questions about the repo.
I had a problem when I want to begin training.It say that  MMCV==1.4.8 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
And I found that there is not mmcv>=2.0.0rc4, <2.2.0 based on torch1.7-cu110.I hope to hear from you,thank you.

**Comment by zgchen33** [comment]
> Thanks a lot to the authors for the wonderful work. I have some quick questions about the repo. I had a problem when I want to begin training.It say that MMCV==1.4.8 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0. And I found that there is not mmcv>=2.0.0rc4, <2.2.0 based on torch1.7-cu110.I hope to hear from you,thank you.

Could you provide me with more information about this issue? For example, where and when does it say that MMCV==1.4.8 is used but incompatible?

**Comment by BmonsterYJ** [comment]
> > Thanks a lot to the authors for the wonderful work. I have some quick questions about the repo. I had a problem when I want to begin training.It say that MMCV==1.4.8 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0. And I found that there is not mmcv>=2.0.0rc4, <2.2.0 based on torch1.7-cu110.I hope to hear from you,thank you.
> 
> Could you provide me with more information about this issue? For example, where and when does it say that MMCV==1.4.8 is used but incompatible?

When I want to retrain the model, i.e. when I run the tools/train.py file, I get the following error:No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
Traceback (most recent call last):
  File "E:\LYJ\MCGaze-master\MCGaze-master\tools\train.py", line 17, in <module>
    from mmdet import __version__
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\mmdet\__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.8 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

**Comment by zgchen33** [comment]
> > > Thanks a lot to the authors for the wonderful work. I have some quick questions about the repo. I had a problem when I want to begin training.It say that MMCV==1.4.8 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0. And I found that there is not mmcv>=2.0.0rc4, <2.2.0 based on torch1.7-cu110.I hope to hear from you,thank you.
> > 
> > 
> > Could you provide me with more information about this issue? For example, where and when does it say that MMCV==1.4.8 is used but incompatible?
> 
> When I want to retrain the model, i.e. when I run the tools/train.py file, I get the following error:No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8' Traceback (most recent call last): File "E:\LYJ\MCGaze-master\MCGaze-master\tools\train.py", line 17, in from mmdet import **version** File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\mmdet__init__.py", line 16, in assert (mmcv_version >= digit_version(mmcv_minimum_version) AssertionError: MMCV==1.4.8 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

@BmonsterYJ After you installed mmcv-full, did you run the commands below?
```
cd MCGaze
pip install -v -e .
```

**Comment by wenzhengzeng** [comment]
I guess maybe there is some incompatibility (e.g., CUDA version, it seems that your CUDA version is 11.8, not 11.0). So please refer to the [lastest branch](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) of the MMCV installation documentation, then choose the correct command based on your actual environment. 
![image](https://github.com/zgchen33/MCGaze/assets/49069169/3338b515-6012-4dee-917f-1c9433c8d6ce)
If this is truly the cause, don't simply replace the old one; uninstall it first.
  ```bash
     pip uninstall mmcv
     pip uninstall mmdet
 ```
You can also refer to [InstBlink](https://github.com/wenzhengzeng/MPEblink?tab=readme-ov-file) to seek possible solutions.
